version: "3.8"
services:
  mongodb:
    image: "mongo"
    volumes:
      - data:/data/db
    #container_name: mongodb
    # environment:
    # MONGODB_USERNAME: max
    # MONGODB_PASSWORD: secret
    #- MONGODB_USERNAME=max
    env_file:
      - ./env/mongo.env
    # networks:
    #   - goals-net
  backend:
    build: ./backend
    #longer form
    # build:
    #   context: ./backend
    #   dockerfile: Dockerfile
    # args:
    #   some-arg: 1
    ports:
      - "80:80"
    volumes:
      - logs:/app/logs #named volume
      - ./backend:/app #bind mount
      - /app/node_modules #anonymous volume
    env_file:
      - ./env/backend.env
    depends_on: #available only on docker-compose, but not in docker run
      - mongodb
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/app/src
    stdin_open: true #tell docker that this service need an open input connection
    tty: true #for attaching a terminal
    depends_on:
      - backend

#named volumes must be specified here.
#anonymous volumes and bind mounts don't need to
#be specified here
volumes:
  data:
  logs:
